# Generated by Django 5.0 on 2024-01-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busness_e_commerce_app', '0004_account_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
