# Generated by Django 5.0 on 2024-01-11 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('busness_e_commerce_app', '0005_account_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
    ]
